name: BuildAndTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run
      working-directory: ./CSShadersTests
      run: ./bin/Debug/netcoreapp3.1/CSShadersTests.exe --artifactsDir "Artifacts"
    - name: Archive Test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        path: ./CSShadersTests/Artifacts
    - name: Test
      run: dotnet test --no-build --verbosity normal
